# services:
#   items_api:
#     container_name: items_api
#     image: node-typescript
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - API_HOST=items_api
#       - PORT=80
#     ports:
#       - "3001:80"
#     entrypoint: ["npm", "run", "dev"]
#     volumes:
#       - ./src:/app/src
#       - ./__tests__:/app/__tests__
